spring.application.name=DecentraBox

spring.profiles.active=local


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

pinata.base-url: https://api.pinata.cloud
pinata.upload-url: https://uploads.pinata.cloud
pinata.signed-url-expiry: 3600

server.port=8080
